# Generated by Django 3.2.9 on 2021-11-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='zipcode',
            new_name='zip_code',
        ),
    ]
